name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --extra-index-url https://download.pytorch.org/whl/cpu torch==2.2.0+cpu torchvision==0.17.0+cpu
        pip install "numpy<2.0" pytest matplotlib pillow psutil
        
    - name: Generate augmentation samples
      run: |
        python src/show_augmentations.py
        
    - name: Train model
      run: |
        python src/train.py
        
    - name: Run tests
      run: |
        pytest src/test_model.py -v
        
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-and-samples
        path: |
          models/
          sample_images/